match_new_names <- function(matchTo){
  
  good.names <- data.table(
    new = c(
      "Age",
      "Sex",
      "log-BMI",
      "WHR",
      "Blood pressure (systolic)",
      "Blood pressure (diastolic)",
      "Pulse pressure",
      "Diabetes status",
      "Self reported diabetes",
      "Diabetes medication",
      "HBa1c",
      "Smoking status",
      ">8 hours since last meal",
      "Sex hormones",
      "Cholesterol",
      "LDL-Cholesterol",
      "HDL-Cholesterol",
      "Leucocytes",
      "Lymphocytes",
      "Monocytes",
      "Hematocrit",
      "Platelets",
      "Reticulocytes",
      "Neutrophils",
      "Erythrocytes",
      "Basophils",
      "Eosinophils",
      "Blood hemoglobin",
      "Lipid modifying agents",
      "Fasting hours"),
    old = c("age",
            "sex",
            "log.bmi",
            "whr",
            "bp.sys",
            "bp.dia",
            "pulse.pressure",
            "diabetes.status.tri",
            "diabetes.anamnese",
            "diabetes.medication",
            "hba1c.percent",
            "smoking.status",
            "fasting.8.hrs",
            "atc.code.g03",
            "cholesterol",
            "ldl.cholesterol",
            "hdl.cholesterol",
            "white.blood.cells",
            "lymphocytes.percent",
            "monocytes.percent",
            "hematocrit",
            "platelets",
            "reticulocytes",
            "neutrophils.percent",
            "erythrocytes",
            "basophils.percent",
            "eosinophils.percent",
            "blood.hemoglobin.level",
            "atc.code.c10",
            "fasting.hours"))
  
  matched.names <- good.names[match(matchTo, old), new]
  
  return(matched.names)
  
}
